### ISSUE TITLE
Problem with quotes

### ISSUE THREAD

**Issue by mgueury** [mgueury/html_validator#31]
I just installed the 0.9.8.3 version, and found a problem with single quotation marks.
Note:  square brackets substituted for angle brackets below

Source code: 
[img src='blah.jpg'] Has single quotes

Validator displays:
[img src="blah.jpg"] Single quotes translated to double

This gets worse when double quotes are enclosed within single quotes:

Source code: 
[img src="blah.jpg" onClick='showBigPic(this, "461x576", "1960x1200", "1920x2400");']

Validator displays:
[img src="blah.jpg" onclick="showBigPic(this, &quot;461x576&quot;, &quot;960x1200&quot;, &quot;1920x2400&quot;);"]

**Comment by mgueury** [comment]
From a first sight, this happen only in FF and not in Chrome.

I think that it will be solved as the same time that this bug who is a Mozilla ER.

https://github.com/mgueury/html_validator/issues/11

**Comment by hennesse** [comment]
Marc - You are correct - On Chrome, Validator works perfectly.

I did a little further research into how Firefox (my favorite) and Chrome handle single/double quotes.  It's rather disheartening.  These are supposed to be "developer tools" to help developers.  Instead, both browsers decide to change code with single quotes rather capriciously, often changing valid code into INvalid code.  


SOURCE

img src="jerry.jpg" onclick="doSomething('parm')"     // double double single
img src='jerry.jpg' onclick='doSomething("parm")'     // single single double


CHROME 62

Elements: on screen display
img src="jerry.jpg" onclick="doSomething('parm')"
img src="jerry.jpg" onclick="doSomething("parm")"     // wrong, invalid

Elements: Copy - element
img src="jerry.jpg" onclick="doSomething('parm')"
img src="jerry.jpg" onclick="doSomething(&quot;parm&quot;)"      // wrong, invalid

Elements: Copy - outer HTML
img src="jerry.jpg" onclick="doSomething('parm')"
img src="jerry.jpg" onclick="doSomething(&quot;parm&quot;)"      // wrong, invalid


Validator - highlight copy
img src="jerry.jpg" onclick="doSomething('parm')"
img src='jerry.jpg' onclick='doSomething("parm")'     // right

Validator - Clean up - original HTML
img src="jerry.jpg" onclick="doSomething('parm')"
img src='jerry.jpg' onclick='doSomething("parm")'     // right

Validator - Clean up - cleaned HTML
img src="jerry.jpg" onclick="doSomething('parm')" alt="#########"
img src='jerry.jpg' onclick='doSomething("parm")' alt="#########"     // right



FIREFOX 57

Page source (ctrl-U)
img src="jerry.jpg" onclick="doSomething('parm')"
img src='jerry.jpg' onclick='doSomething("parm")'     // right

Inspector: on screen display
img src="jerry.jpg" onclick="doSomething('parm')"
img src="jerry.jpg" onclick='doSomething("parm")'     // wrong, but valid

Inspector: copy outer HTML
img src="jerry.jpg" onclick="doSomething('parm')"
img src="jerry.jpg" onclick="doSomething(&quot;parm&quot;)"     // wrong, invalid


Validator: highlight copy
img src="jerry.jpg" onclick="doSomething('parm')"
img src="jerry.jpg" onclick="doSomething(&quot;parm&quot;)"     // wrong due to FF bug

Validator: clean up - original HTML
img src="jerry.jpg" onclick="doSomething('parm')"
img src="jerry.jpg" onclick="doSomething(&quot;parm&quot;)"     // wrong due to FF bug

Validator: clean up - cleaned HTML
img src="jerry.jpg" onclick="doSomething('parm')" alt="#########"
img src="jerry.jpg" onclick="doSomething(&quot;parm&quot;)" alt="#########"     // wrong due to FF bug

**Comment by mgueury** [comment]
Thanks for your tests. Based on them, I close this as duplicate of #11.
