### ISSUE TITLE
HTML Validator not working on FF 60 and on Chrome 66

### ISSUE THREAD

**Issue by alecos71** [mgueury/html_validator#57]
# **_On Windows 10:_**

With FF 60 still sees the source generated by browser instead source generated by server. The Options of this extension are partial broken... not able to select GSML, always gets TIDY... partial working on FF 60, needs to be reworked again to be useful under FF 60 and more...

In chrome this extension don't work anymore... won't validate my web pages, instead to see a green flag I can see only a message "Info 0 0 No HTML" and nothing other... the flag remains gray... I'm not able to select SGML parser instead of TIDY.

I attach some screenshots...

**Chrome 66.0.3359.181**

![html validator 01](https://user-images.githubusercontent.com/9997666/40223326-f1fa8404-5a82-11e8-90ab-141eddca5bd3.png)
![html validator 02](https://user-images.githubusercontent.com/9997666/40223327-f2191fb8-5a82-11e8-92dd-1bd19964cbc3.png)
![html validator 03](https://user-images.githubusercontent.com/9997666/40223328-f235550c-5a82-11e8-8ab3-c454ea4b1a97.png)

**FireFox 60.0.1**

![html validator 04](https://user-images.githubusercontent.com/9997666/40223430-55cd7892-5a83-11e8-84f7-15cbce627c69.png)
![html validator 05](https://user-images.githubusercontent.com/9997666/40223432-55eb7c20-5a83-11e8-80b6-6ee3bf99166d.png)
![html validator 06](https://user-images.githubusercontent.com/9997666/40223433-560759b8-5a83-11e8-99ce-ffacbd003979.png)

**Comment by mgueury** [comment]
There are 2 differents issues:
**_Issue 1 : SGML Parser_**
- I am still hesitating to put back the SGML parser. 
  It is not part of the extension anymore. Since FF57, binary code can not be included in an extension anymore.
  So, I have compiled Tidy from C to Javascript to still validate locally.
  I have recompiled the SGML Parser from C to javascript too but it is hugely complex 
   - it requires a javascript filesystem 
   - it does not support HTML 5.
   - it is huge 8MB I think. What would increase the size of the extension and make it slower.
- The new version of Tidy (since FF57) does support HTML5.

Currently, unless big request, I do not think to put it back. The extension would be about 5 times bigger to 10MB for something that does not support HTML5. I think more to remove the reference to it in the welcome screen.

**_Issue 2    Info 0 0 no HTML._** 
This is because the HTML cache of the browser is empty. If you go in the developer panel, tab "Source " from Chrome, you will see that there is the same problem. 
Please refresh your browser when this happen, it will get the HTML sent by the server with the validation result.

Maybe the message should be different ? The Source of Chrome says nothing neither ?
Should I add a second message to ask to reload the page ?

What do you think for the both points above ?

Thanks,

**Comment by alecos71** [comment]
1) Hi! I'd like to have sgml parser since I develop web pages in html 401, xhtml 1.1 and finally html5 but I prefer to develop in html 401 and xhtml 1.1. So I need sgml parser.

2) The cache is not empty and the issue appears only on my website but other webpages of my site are checked well... I suspect that some elements present in the source make your app in tilt...

3) I think that you don't need to inform to reload the page since I think is a bug...

Test yourself https://www.alecos.it/

**Comment by alecos71** [comment]
Hi! I just tested again Chrome, latest version. When "Issue 2 Info 0 0 no HTML" happens just reloading the web page makes your validator working fine. If I close or quit Chrome and then try to validate my web page again I have to reload the page to see the result!!! On Chrome your validator is better than on Firefox...

I hope you can fix the issue so I don't need to reload the page, on Firefox I don't need to reload the page to see the result, I hope to see fixed this bug on Chrome and on Firefox.

Happy week-end!

**Comment by mgueury** [comment]
Thanks for the feedback. 

For Firefox, 

I have to wait for Mozilla to fix bug https://bugzilla.mozilla.org/show_bug.cgi?id=1361121
See issue #11 

For Chrome, 

I will change the behavior and make it clear that Chrome cache being empty that you need reload the page. Maybe I should log a bug in Chrome too. To be confirmed.

**Comment by mgueury** [comment]
Project moved to Gitlab.
See https://gitlab.com/mgueury/html_validator/issues/57
